### ISSUE TITLE
does not seem to be running

### ISSUE THREAD

**Issue by GiorgosK** [digitalpianism/bugfixes#2]
copied the app directory over the magento root directory 
all files seem to be in place but the bugfixes do not seem to work

I have tried to 

> ./mage clear-cache

logout and log in and clear the cache from within the admin interface 

looking in the magento connect manager there is no indication that the module is actually installed

the reason I installed this bugfixes was really to solve the "Undefined index session_expire_timestamp" problem but does not seem to work 

any ideas

**Comment by GiorgosK** [comment]
the module can be seen in the config > advanced > advanced section as enabled ?!

**Comment by digitalpianism** [comment]
@GiorgosK interesting issue, do you have compilation enabled maybe ? Basically the "module" is only for the controllers issues. The rest of the bug fixes are overrides and located under `app/code/local`

**Comment by GiorgosK** [comment]
@digitalpianism no compiler is disabled (should have said that before)
I am not that experienced with magento, but yes I realized they are overrides 
when I applied manually the patch found here https://tomlankhorst.nl/fix-magento-undefined-index-session_expire_timestamp/ it really worked, but with this module it does not seem to work

is there anything else I can check ?

**Comment by digitalpianism** [comment]
@GiorgosK it worked but it is not recommended at all to edit the `app/code/core` files because you will loose the changes in those files when you upgrade and you'll face conflicts when patching. So do you have the `app/code/local/Mage/Core/Model/Session/Abstract/Varien.php` in your Magento folder ?

**Comment by GiorgosK** [comment]
well the files are all there 
maybe the file/folder permissions are not right ?
is there a ./mage command that sets all permissions RIGHT

**Comment by digitalpianism** [comment]
@GiorgosK doesn't sound like a permission problem to me. Could you try to copy `app/code/core/Mage/Core/Model/Session/Abstract/Varien.php` to `app/code/local/Mage/Core/Model/Session/Abstract/Varien.php` and apply the fix here manually see if it works: https://tomlankhorst.nl/fix-magento-undefined-index-session_expire_timestamp/

**Comment by GiorgosK** [comment]
Yes it works 
it seems you not replacing the if block with the one he is proposing 

<pre>
if ($this->useValidateSessionExpire() ) {
    // If the VALIDATOR_SESSION_EXPIRE_TIMESTAMP key is not set, do it now
    if( !isset($sessionData[self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP]) ) {
        // $this->_data is a reference to the $_SESSION variable so it will be automatically modified
        $this->_data[self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP] = time() + $this->getCookie()->getLifetime();
        return true;
    } elseif ( $sessionData[self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP] < time() ) {
        return false;
    }
} else {
    $this->_data[self::VALIDATOR_KEY][self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP]
        = $validatorData[self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP];
}</pre>

**Comment by digitalpianism** [comment]
@GiorgosK oh I see he updated his code 12 hours ago that's why ! I'll update the code right now thanks for your issue ;)

**Comment by GiorgosK** [comment]
@digitalpianism ha ha nice I was pulling my hair out since I am not experienced thought it was something I did ... thanks for helping resolve it
