### ISSUE TITLE
Another Soap Error

### ISSUE THREAD

**Issue by jorgb90** [digitalpianism/bugfixes#3]
We just upgraded to 1.9.3.0 and are also experiencing API errors. Added your fix and it works but still got another error:

Got error 'PHP message: PHP Fatal error:  SOAP-ERROR: Encoding: Cannot find encoding in /home/65281-54366/wnwamytwex/public_html/lib/Zend/Soap/Server.php on line 889\n'

Are you guys that seeing as well? We are running PHP 7.

**Comment by digitalpianism** [comment]
@jorgb90 Hi and thanks for your issue. Haven't seen that error yet. Could you provide a procedure so I can replicate the issue ?

**Comment by jorgb90** [comment]
@digitalpianism We need to further debug it. We are not certain yet if its a main Magento problem or the problem is in a extension which extends the API for Hublogix.

The only thing we see in the logs at the moment is that accessing the api returns a error 500.

`"POST /index.php" 500 573 - 20890 27031 0.063 2097152 94.68% 0.00% "/index.php/api/index/index/"`

And the error is:

`'PHP message: PHP Fatal error: SOAP-ERROR: Encoding: Cannot find encoding in /home/65281-54366/wnwamytwex/public_html/lib/Zend/Soap/Server.php on line 889\n'`

**Comment by digitalpianism** [comment]
@jorgb90 thanks for the details. Please update this issue when you have further debugged the problem. Do you confirm that problem was not present on 1.9.2.4 ?

**Comment by jorgb90** [comment]
@digitalpianism Confirmed. The problem was not present on 1.9.2.4.

**Comment by digitalpianism** [comment]
@jorgb90 ok thanks for that. As of now, I don't have time to debug unknown issues without a good debug procedure to replicate the bug so I leave the issue open while you work on further debugging ;)

**Comment by jorgb90** [comment]
@digitalpianism We are stuck we aren't capable to debug it ourselves.. We should hire some help :(

**Comment by jorgb90** [comment]
@digitalpianism We got a official response from HubLogix:

"We have had a couple other customers try to upgrade Magento and are experiencing the similar issues. I am passing your request along to our development team who can look into this. Please keep in mind it may take some time to research the issue before we have a resolution."

**Comment by digitalpianism** [comment]
@jorgb90 ok so definitely related to the module, I can close the issue

**Comment by jorgb90** [comment]
The SOAP-ERROR was not related! Fixed it with this piece of code thanks to [tobihille](https://github.com/Inchoo/Inchoo_PHP7/issues/79#issuecomment-254504096);

**Comment by digitalpianism** [comment]
@jorgb90 oh I see, I've updated the repo to reflect that change thanks for the update ;)

**Comment by jorgb90** [comment]
@digitalpianism Great! :)

**Comment by joolswills** [comment]
the fix here - https://github.com/Inchoo/Inchoo_PHP7/issues/79#issuecomment-254504096 works for me, but the fix in this repository here does not - eg when calling

`shoppingCartShippingList($sessionId, $cartId);`

with the code from tobihille i get something like this returned

```
array(4) {
  [0]=>
  object(stdClass)#3 (6) {
    ["code"]=>
    string(46) "royalmail_UK_STANDARD_FIRST_CLASS_SMALL_PARCEL"
    ["carrier"]=>
    string(9) "royalmail"
    ["carrier_title"]=>
    string(10) "Royal Mail"
    ["method"]=>
    string(36) "UK_STANDARD_FIRST_CLASS_SMALL_PARCEL"
    ["method_title"]=>
    string(33) "Standard First Class Small Parcel"
    ["price"]=>
    float(4.04)
  }

etc
```

with the code in this repo from https://github.com/digitalpianism/bugfixes/commit/79f130e433f3ee3b70c54035ca98fed5bd95aba4

I get

```
array(4) {
  [0]=>
  object(stdClass)#3 (0) {
  }
```

not dug into the code yet.

**Comment by digitalpianism** [comment]
@joolswills thanks for that I have updated the bug fix based on @bubach answer

**Comment by digitalpianism** [comment]
@joolswills made another updated based on @tobihille answer

**Comment by jorgb90** [comment]
@digitalpianism @joolswills It was the solution I already referred to see the link in @tobihille name in my comment :) But glad its sorted out now!

**Comment by bjoern-tantau** [comment]
I think this is actually a PHP bug. Updating to PHP 7.0.12 fixed it for me. Otherwise you might encounter the problem in other places as well.

**Comment by digitalpianism** [comment]
@bjoern-tantau interesting. Was the problem still present when you applied the fix ?

**Comment by bjoern-tantau** [comment]
Yes. Though I don't use this extension, I just had it when calling order.info. I came here from Stackoverflow.

**Comment by digitalpianism** [comment]
@bjoern-tantau well there's definitely a SOAP API bug with 1.9.3 as upgrading broke stuff on several websites and people reported the issue. Whether or not the fix in this repo is the right one it's hard to say
