### ISSUE TITLE
patch for bundles that fix price incl tax on frontend?

### ISSUE THREAD

**Issue by tomekjordan** [digitalpianism/bugfixes#5]
Hi any option to add fix for bundles prices that comes without tax when admin prices are set without tax, but frontend show incl tax? bug appears on category as low as prices and for product page prices. magento didnt fix it for 2years...

**Comment by digitalpianism** [comment]
@tomekjordan Hi and thanks for your issue. The purpose of this module is to fix the bugs that have been introduced by 1.9.3.0 . If your bug has been here before 1.9.3.0 we won't try to fix it. If you think it has been introduced by 1.9.3.0 please provide a procedure to replicate it and explain the actual results on 1.9.2.4 and the "buggy" results on 1.9.3.0
