### ISSUE TITLE
Bad model name monthly customer cron task

### ISSUE THREAD

**Issue by jaminion** [digitalpianism/bugfixes#6]
Hello, didn't know where else I might drop this as Magento's bug tracking system appears to currently be offline, and I was hoping to make sure someone was aware of this before the potential 1.9.3.1 drop for CE, hopefully someone with a better channel to Magento support.

As part of the customer password reset process that they updated in 1.9.3.0, they have a cleanup function to clean up the ip/attempt tracking table customer_flowpassword. They've added a monthly cron task to run that function defined in app/code/core/Mage/Customer/etc/config.xml. Unfortunately they reference the observer model as "mage_customer/observer" instead of "customer/observer", so I've found this in logs today for sites where they have had the full 1.9.3.0 update applied:

Warning: include(): Failed opening 'Mage/Mage/Customer/Model/Observer.php' for inclusion

I'm not aware of a way to remove the crontab reference through xml-fu, but it would be easy enough to add the cron task to another module such as this one.

I must also say: Raphael, thank you very much for all your efforts with the issues around update 1.9.3.0, you have done a tremendous job centralizing and clarifying all of that information.

**Comment by digitalpianism** [comment]
@jaminion fixed in the new version, thanks for creating the issue

**Comment by rafaelpatro** [comment]
Thanks for share! Great work

Simple fix if you have AOE_Scheduler installed.
Go to _System > Scheduler > Job Configuration > Edit Job "customer_flowpassword"_:

![image](https://cloud.githubusercontent.com/assets/13813964/19977189/ef195a20-a1d9-11e6-90b0-481f93002568.png)

Have a nice day
