### ISSUE TITLE
product images upload

### ISSUE THREAD

**Issue by yasinkocak** [digitalpianism/bugfixes#8]
I'm using Magento 1.9.3 and i have issue with product images upload.

U can see the loading of upload to 100% but is not uploaded. I have checked my permission of folders. This is still correct.

Is there knowing issue with upload in magento 1.9.3?

**Comment by digitalpianism** [comment]
@yasincokak no I made some tests and there is no such issue known on a fresh 1.9.3 install you should try to ask your question and problem on Magento stack exchange and Magento Forums.

**Comment by Lach1222** [comment]
Had this same issue but was able to fix it using this

https://community.magento.com/t5/Security-Patches/SUPEE-8788-Solutions-to-Different-Problems/m-p/52572#U52572
